version: '3'
services:
  
  dbstg:
    container_name: ${MARIADB_SERVER_STG}
    image: mariadb:jammy
    restart: always
    volumes:
      - ./mariadb-stg-data:/var/lib/mysql
    environment:
      MYSQL_USER: ${USERNAME_MARIADB_STG}
      MYSQL_PASSWORD: ${PASSWORD_MARIADB_STG}
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MARIADB_STG}
    command: >
      bash -c "
        /entrypoint.sh mysqld & sleep 10s
        && mysql -u root -p${PASSWORD_ROOT_MARIADB_STG} -e '
          CREATE DATABASE IF NOT EXISTS Test;
          USE Test;
          CREATE TABLE IF NOT EXISTS sys_Message (
            PKMessage INT AUTO_INCREMENT PRIMARY KEY,
            message_text VARCHAR(50) NOT NULL
          );'
        && wait"

  dbprd:
    container_name: ${MARIADB_SERVER_PRD}
    image: mariadb:jammy
    restart: always
    volumes:
      - ./mariadb-prd-data:/var/lib/mysql
    environment:
      MYSQL_USER: ${USERNAME_MARIADB_PRD}
      MYSQL_PASSWORD: ${PASSWORD_MARIADB_PRD}
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MARIADB_PRD}

  phpmyadmin:
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    depends_on:
      - dbstg
      - dbprd
    image: phpmyadmin:5.2.1-apache
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
  httpd:
    container_name: ${HTTPD_CONTAINER_NAME}
    image: httpd:alpine3.18
    restart: always
    ports:
      - "${HTTPD_PORT}:80"
    volumes:
      - ./http-folder:/usr/local/apache2/htdocs
  python:
    container_name: ${PYTHON_CONTAINER_NAME}
    image: python:alpine3.17
    restart: always
    ports:
      - "${PYTHON_PORT}:8000"
    volumes:
      - ./python-folder:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: sh -c "python3 -m venv /appenv &&
     source /appenv/bin/activate &&
      pip install fastapi uvicorn &&
      pip install mysql-connector-python &&
       uvicorn app:app --host 0.0.0.0 --port 8000"
volumes:
  #genera volumnes fisicos cuando no existen si pones external true los ba a buscar y si no los encuentra
  #no arranca 
  mariadb-stg-data:
  mariadb-prd-data:
  http-folder:
  python-folder: